.TH d2id 1
.SH NAME
d2id \- Send data from a DS18B20 to Influx DB
.SH SYNOPSIS
.B d2id [options]
[\fB\-n\fR \fIBITS\fR]
[\fB\-\-bits\fR \fIBITS\fR]
.IR file ...
.SH DESCRIPTION
.B d2id
Send temperatures from up to 10 DS18B20 to InfluxDB
.SH OPTIONS
.TP
.BR \-h ", " \-\-help =\fadsf\fR
Print help.
.BR \-c ", " \-\-config =\path\fR
Set Path to config file
